// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations.VaultDb
{
    [DbContext(typeof(VaultDbContext))]
    [Migration("20260925005647_dataVencimento")]
    partial class dataVencimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Corretoras.Corretora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("CorretoraId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Corretoras", (string)null);
                });

            modelBuilder.Entity("Domain.Emissores.Emissor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("EmissorId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Emissores", (string)null);
                });

            modelBuilder.Entity("Domain.Movimentos.Movimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("MovimentoId");

                    b.Property<Guid>("CorretoraId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CorretoraId");

                    b.Property<string>("CotacaoNaCompra")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime>("DataInvestimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EhReinvestimento")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("EmissorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("EmissorId");

                    b.Property<bool>("EstaAtivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ObjetivoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ObjetivoId");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ProdutoId");

                    b.Property<string>("RentabilidadeContratada")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("TipoRendaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("TipoRendaId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.Property<decimal>("ValorAporte")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquidoAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CorretoraId");

                    b.HasIndex("EmissorId");

                    b.HasIndex("ObjetivoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("TipoRendaId");

                    b.HasIndex("UserId", "CorretoraId");

                    b.HasIndex("UserId", "EmissorId");

                    b.HasIndex("UserId", "ObjetivoId");

                    b.HasIndex("UserId", "ProdutoId");

                    b.HasIndex("UserId", "TipoRendaId");

                    b.ToTable("Movimentos", (string)null);
                });

            modelBuilder.Entity("Domain.Objetivos.Objetivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ObjetivoId");

                    b.Property<decimal>("AporteMensal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FontePagadora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Meta")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OndeAplicar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Objetivos", (string)null);
                });

            modelBuilder.Entity("Domain.Produtos.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ProdutoId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Domain.TiposRenda.TipoRenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("TipoRendaId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TiposRenda", (string)null);
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "1c9f342a-182f-4100-bcdd-3e44950c0d59",
                            ConcurrencyStamp = "9cc36c17-7d58-4813-9709-897e039cc690",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Domain.Corretoras.Corretora", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Corretoras")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Emissores.Emissor", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Emissores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Movimentos.Movimento", b =>
                {
                    b.HasOne("Domain.Corretoras.Corretora", "Corretora")
                        .WithMany("Movimentos")
                        .HasForeignKey("CorretoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Emissores.Emissor", "Emissor")
                        .WithMany("Movimentos")
                        .HasForeignKey("EmissorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Objetivos.Objetivo", "Objetivo")
                        .WithMany("Movimentos")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Produtos.Produto", "Produto")
                        .WithMany("Movimentos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.TiposRenda.TipoRenda", "TipoRenda")
                        .WithMany("Movimentos")
                        .HasForeignKey("TipoRendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany("Movimentos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corretora");

                    b.Navigation("Emissor");

                    b.Navigation("Objetivo");

                    b.Navigation("Produto");

                    b.Navigation("TipoRenda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Objetivos.Objetivo", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Objetivos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Produtos.Produto", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Produtos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.TiposRenda.TipoRenda", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("TiposRenda")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Corretoras.Corretora", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("Domain.Emissores.Emissor", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("Domain.Objetivos.Objetivo", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("Domain.Produtos.Produto", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("Domain.TiposRenda.TipoRenda", b =>
                {
                    b.Navigation("Movimentos");
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Navigation("Corretoras");

                    b.Navigation("Emissores");

                    b.Navigation("Movimentos");

                    b.Navigation("Objetivos");

                    b.Navigation("Produtos");

                    b.Navigation("TiposRenda");
                });
#pragma warning restore 612, 618
        }
    }
}
