// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(VaultDbContext))]
    partial class VaultDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Bancos.Banco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("BancoId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Bancos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bcc25e6-e003-442d-8aa4-a857863800b5"),
                            Nome = "Inter"
                        },
                        new
                        {
                            Id = new Guid("1965ec96-158a-4c51-b51a-c0bed101e28a"),
                            Nome = "NuBank"
                        },
                        new
                        {
                            Id = new Guid("a5c434b8-c955-44de-960a-416387167689"),
                            Nome = "Caixa"
                        },
                        new
                        {
                            Id = new Guid("d6b51592-fe68-4cef-8cda-73628c1d1094"),
                            Nome = "Mercado Pago"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
